# ============================================================================
# Help Target
# ============================================================================

.PHONY: help

help: ## Show this help
	@echo ""
	@echo "$(BOLD)$(PROJECT_NAME) Makefile$(RESET)"
	@echo ""
	@echo "$(BOLD)$(CYAN)Development:$(RESET)"
	@echo "  $(GREEN)up$(RESET)                 Start the full stack (Jellyfin + session server)"
	@echo "  $(GREEN)down$(RESET)               Stop all services"
	@echo "  $(GREEN)restart$(RESET)            Restart all services"
	@echo "  $(GREEN)restart-jellyfin$(RESET)   Restart Jellyfin only (after JS changes)"
	@echo "  $(GREEN)restart-server$(RESET)     Rebuild and restart session server"
	@echo "  $(GREEN)dev$(RESET)                Start stack and follow logs"
	@echo "  $(GREEN)watch$(RESET)              Watch JS files and auto-restart on change"
	@echo "  $(GREEN)shell-jellyfin$(RESET)     Open shell in Jellyfin container"
	@echo "  $(GREEN)shell-server$(RESET)       Open shell in session server container"
	@echo ""
	@echo "$(BOLD)$(CYAN)Build:$(RESET)"
	@echo "  $(GREEN)build$(RESET)              Build the Jellyfin plugin"
	@echo "  $(GREEN)build-server$(RESET)       Build the session server locally (Rust)"
	@echo "  $(GREEN)build-server-docker$(RESET) Rebuild session server Docker image"
	@echo "  $(GREEN)build-all$(RESET)          Build everything (plugin + server image)"
	@echo "  $(GREEN)rebuild$(RESET)            Clean and rebuild everything"
	@echo "  $(GREEN)release$(RESET)            Build release artifacts (zip)"
	@echo "  $(GREEN)release-image$(RESET)      Build release Docker image (prod)"
	@echo ""
	@echo "$(BOLD)$(CYAN)Observability:$(RESET)"
	@echo "  $(GREEN)logs$(RESET)               Follow logs from all services"
	@echo "  $(GREEN)logs-server$(RESET)        Follow session server logs only"
	@echo "  $(GREEN)logs-jellyfin$(RESET)      Follow Jellyfin logs only"
	@echo "  $(GREEN)status$(RESET)             Show service status with health info"
	@echo "  $(GREEN)health$(RESET)             Check health of all services"
	@echo "  $(GREEN)stats$(RESET)              Show container resource usage (CPU/mem)"
	@echo "  $(GREEN)top$(RESET)                Show running processes in containers"
	@echo "  $(GREEN)connections$(RESET)        Show active WebSocket connections"
	@echo ""
	@echo "$(BOLD)$(CYAN)Testing & Quality:$(RESET)"
	@echo "  $(GREEN)test$(RESET)               Run all tests"
	@echo "  $(GREEN)lint$(RESET)               Run all linters (Rust + JS)"
	@echo "  $(GREEN)fmt$(RESET)                Format all code"
	@echo "  $(GREEN)check$(RESET)              Run cargo check (fast compile check)"
	@echo "  $(GREEN)pre-commit$(RESET)         Run all pre-commit hooks"
	@echo ""
	@echo "$(BOLD)$(CYAN)Setup & Cleanup:$(RESET)"
	@echo "  $(GREEN)setup$(RESET)              Setup development environment"
	@echo "  $(GREEN)setup-hooks$(RESET)        Install pre-commit hooks"
	@echo "  $(GREEN)clean$(RESET)              Clean all build artifacts"
	@echo "  $(GREEN)clean-docker$(RESET)       Remove Docker images and volumes"
	@echo "  $(GREEN)reset$(RESET)              Full reset (containers + artifacts)"
	@echo "  $(GREEN)prune$(RESET)              Remove unused Docker resources"
	@echo "  $(GREEN)fix-permissions$(RESET)    Fix ownership of Docker-created files"
	@echo ""
	@echo "$(BOLD)$(CYAN)Utilities:$(RESET)"
	@echo "  $(GREEN)info$(RESET)               Show project information"
	@echo "  $(GREEN)env$(RESET)                Show environment variables"
	@echo "  $(GREEN)urls$(RESET)               Show service URLs"
	@echo "  $(GREEN)tree$(RESET)               Show project structure"
	@echo ""
	@echo "$(BOLD)$(CYAN)Quick Aliases:$(RESET)  $(GREEN)u$(RESET)=up  $(GREEN)d$(RESET)=down  $(GREEN)r$(RESET)=restart  $(GREEN)l$(RESET)=logs  $(GREEN)s$(RESET)=status  $(GREEN)b$(RESET)=build"
	@echo ""
