use super::constants::CLIENT_CHANNEL_BUFFER;
use super::dispatch::client_msg;
use crate::auth::JwtConfig;
use crate::messaging::{send_room_list, send_to_client};
use crate::password::ct_eq;
use crate::types::{ClientReceiver, ClientSender, Clients, OutboundMessage, Rooms, WsMessage};
use crate::utils::{now_ms, random_token};
use axum::extract::ws::{Message, WebSocket};
use futures::StreamExt;
use log::{info, warn};
use std::sync::Arc;
use tokio::sync::mpsc;
use tokio_stream::wrappers::ReceiverStream;

fn register_client(
    client_sender: ClientSender,
    jwt_config: &Arc<JwtConfig>,
) -> crate::types::Client {
    let now = now_ms();
    let authenticated = !jwt_config.enabled;
    let (user_id, user_name) = if authenticated {
        ("anonymous".to_string(), "Anonymous".to_string())
    } else {
        ("".to_string(), "".to_string())
    };

    crate::types::Client {
        sender: client_sender,
        room_id: None,
        user_id,
        user_name,
        authenticated,
        message_count: 0,
        last_reset: now,
        last_seen: now,
        resume_secret: random_token(),
        connected_at: now,
        kind: crate::types::ClientKind::Web,
    }
}

/// Greets a client with its id and resume secret. Only this client ever
/// sees the secret; other members only learn its id (via `participants`).
fn send_client_hello(
    client_id: &str,
    locked_clients: &std::collections::HashMap<String, crate::types::Client>,
) {
    let resume_secret = locked_clients
        .get(client_id)
        .map(|c| c.resume_secret.clone())
        .unwrap_or_default();
    send_to_client(
        client_id,
        locked_clients,
        &WsMessage {
            msg_type: "client_hello".to_string(),
            room: None,
            client: Some(client_id.to_string()),
            payload: Some(serde_json::json!({
                "client_id": client_id,
                "resume_secret": resume_secret,
            })),
            ts: now_ms(),
            server_ts: Some(now_ms()),
        },
    );
}

/// How a new connection relates to an existing client entry.
#[derive(Debug, PartialEq, Eq)]
enum Attach {
    /// Same id and the right secret: take over the entry.
    Reattach,
    /// No entry under this id: register a fresh one with it.
    Register,
    /// The id is in use and the secret doesn't match: refuse the takeover
    /// and hand out a different id instead.
    Refuse,
}

fn decide_attach(existing: Option<&crate::types::Client>, resume: Option<&str>) -> Attach {
    match existing {
        None => Attach::Register,
        // A bridged Jellyfin device is driven in-process; no socket may
        // ever take its place.
        Some(c) if c.kind == crate::types::ClientKind::Bridge => Attach::Refuse,
        Some(c) => match resume {
            Some(r) if ct_eq(r.as_bytes(), c.resume_secret.as_bytes()) => Attach::Reattach,
            _ => Attach::Refuse,
        },
    }
}

/// A client-supplied ID is only trusted if it actually looks like a UUIDv4
/// string generated by our own client (36 chars, hex + hyphens). Anything
/// else falls back to a freshly minted server-side ID. This isn't a secrecy
/// boundary (the ID is a bearer identifier, same trust model as a session
/// cookie) — it's just a sanity filter against garbage/oversized input.
fn is_plausible_client_id(id: &str) -> bool {
    id.len() == 36 && id.chars().all(|c| c.is_ascii_hexdigit() || c == '-')
}

pub async fn client_connection(
    ws: WebSocket,
    clients: Clients,
    rooms: Rooms,
    jwt_config: Arc<JwtConfig>,
    requested_client_id: Option<String>,
    resume_secret: Option<String>,
) {
    let (client_ws_sender, mut client_ws_rcv) = ws.split();
    let (client_sender, client_rcv): (ClientSender, ClientReceiver) =
        mpsc::channel(CLIENT_CHANNEL_BUFFER);

    // The queue carries framework-agnostic `OutboundMessage`s; this is the one
    // place that turns them into transport frames. Each one goes out as a
    // single unfragmented text frame — the plugin's bridges reassemble
    // continuation frames by decoding each chunk independently, so splitting a
    // message here would risk cutting a multi-byte UTF-8 sequence in half.
    let outbound = ReceiverStream::new(client_rcv)
        .map(|msg: OutboundMessage| Ok(Message::Text(msg.into_text().into())));

    tokio::task::spawn(async move {
        let _ = outbound.forward(client_ws_sender).await;
    });

    let mut client_id = requested_client_id
        .filter(|id| is_plausible_client_id(id))
        .unwrap_or_else(|| uuid::Uuid::new_v4().to_string());

    // If this ID already has an entry (a prior connection that's within its
    // reconnect grace period, or a stale one the zombie reaper hasn't gotten
    // to yet) and the caller proves it owns it with the resume secret,
    // reattach: swap in the new transport and keep whatever room membership
    // and role it had. A known id without the right secret is someone else's
    // session (ids are visible to everyone in a room), so that connection
    // gets a fresh id instead of taking the entry over.
    let rejoined_room_id = {
        let mut locked_clients = clients.write().await;
        match decide_attach(locked_clients.get(&client_id), resume_secret.as_deref()) {
            Attach::Reattach => {
                info!("Client {} reconnected (reattaching)", client_id);
                let existing = locked_clients
                    .get_mut(&client_id)
                    .expect("checked by decide_attach");
                existing.sender = client_sender;
                existing.last_seen = now_ms();
                existing.room_id.clone()
            }
            attach => {
                if attach == Attach::Refuse {
                    warn!(
                        "Client id {} is in use and no valid resume secret was given; \
                         issuing a new id",
                        client_id
                    );
                    client_id = uuid::Uuid::new_v4().to_string();
                }
                info!(
                    "Client {} connected (auth_required: {})",
                    client_id, jwt_config.enabled
                );
                let client = register_client(client_sender, &jwt_config);
                locked_clients.insert(client_id.clone(), client);
                None
            }
        }
    };

    {
        let locked_clients = clients.read().await;
        send_client_hello(&client_id, &locked_clients);
    }

    send_room_list(&client_id, &clients, &rooms).await;

    if let Some(room_id) = rejoined_room_id {
        crate::room::resend_room_state(&client_id, &room_id, &clients, &rooms).await;
    }

    while let Some(result) = client_ws_rcv.next().await {
        if let Ok(msg) = result {
            client_msg(&client_id, msg, &clients, &rooms, &jwt_config).await;
        }
    }

    crate::room::schedule_disconnect(client_id, clients, rooms).await;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn register_client_jwt_disabled() {
        let (tx, _rx) = mpsc::channel(10);
        let jwt_config = Arc::new(JwtConfig {
            secret: String::new(),
            audience: "test".to_string(),
            issuer: "test".to_string(),
            enabled: false,
        });
        let client = register_client(tx, &jwt_config);
        assert!(client.authenticated);
        assert_eq!(client.user_id, "anonymous");
        assert_eq!(client.user_name, "Anonymous");
    }

    #[test]
    fn register_client_jwt_enabled() {
        let (tx, _rx) = mpsc::channel(10);
        let jwt_config = Arc::new(JwtConfig {
            secret: "some-secret".to_string(),
            audience: "test".to_string(),
            issuer: "test".to_string(),
            enabled: true,
        });
        let client = register_client(tx, &jwt_config);
        assert!(!client.authenticated);
        assert_eq!(client.user_id, "");
        assert_eq!(client.user_name, "");
    }

    #[test]
    fn plausible_client_id_accepts_uuid() {
        assert!(is_plausible_client_id(
            "550e8400-e29b-41d4-a716-446655440000"
        ));
    }

    #[test]
    fn decide_attach_requires_the_resume_secret() {
        let (tx, _rx) = mpsc::channel(10);
        let jwt_config = Arc::new(JwtConfig {
            secret: String::new(),
            audience: "test".to_string(),
            issuer: "test".to_string(),
            enabled: false,
        });
        let existing = register_client(tx, &jwt_config);
        let secret = existing.resume_secret.clone();

        assert_eq!(decide_attach(None, None), Attach::Register);
        assert_eq!(decide_attach(None, Some("whatever")), Attach::Register);
        assert_eq!(
            decide_attach(Some(&existing), Some(&secret)),
            Attach::Reattach
        );
        // Knowing someone's client id (it's in every participants list) is
        // not enough to take over their session.
        assert_eq!(decide_attach(Some(&existing), None), Attach::Refuse);
        assert_eq!(decide_attach(Some(&existing), Some("")), Attach::Refuse);
        assert_eq!(
            decide_attach(Some(&existing), Some(&"0".repeat(64))),
            Attach::Refuse
        );
    }

    #[test]
    fn register_client_issues_a_resume_secret() {
        let (tx, _rx) = mpsc::channel(10);
        let jwt_config = Arc::new(JwtConfig {
            secret: String::new(),
            audience: "test".to_string(),
            issuer: "test".to_string(),
            enabled: false,
        });
        let a = register_client(tx.clone(), &jwt_config);
        let b = register_client(tx, &jwt_config);
        assert_eq!(a.resume_secret.len(), 64);
        assert_ne!(a.resume_secret, b.resume_secret);
    }

    #[test]
    fn plausible_client_id_rejects_garbage() {
        assert!(!is_plausible_client_id("not-a-uuid"));
        assert!(!is_plausible_client_id(""));
        assert!(!is_plausible_client_id(&"a".repeat(500)));
    }
}
