use super::constants::CLIENT_CHANNEL_BUFFER;
use super::dispatch::client_msg;
use crate::auth::JwtConfig;
use crate::messaging::{send_room_list, send_to_client};
use crate::types::{Clients, Rooms, WsMessage};
use crate::utils::now_ms;
use futures::StreamExt;
use log::info;
use std::sync::Arc;
use tokio::sync::mpsc;
use tokio_stream::wrappers::ReceiverStream;

fn register_client(
    client_sender: mpsc::Sender<Result<warp::ws::Message, warp::Error>>,
    jwt_config: &Arc<JwtConfig>,
) -> crate::types::Client {
    let now = now_ms();
    let authenticated = !jwt_config.enabled;
    let (user_id, user_name) = if authenticated {
        ("anonymous".to_string(), "Anonymous".to_string())
    } else {
        ("".to_string(), "".to_string())
    };

    crate::types::Client {
        sender: client_sender,
        room_id: None,
        user_id,
        user_name,
        authenticated,
        message_count: 0,
        last_reset: now,
        last_seen: now,
    }
}

fn send_client_hello(
    client_id: &str,
    locked_clients: &std::collections::HashMap<String, crate::types::Client>,
) {
    send_to_client(
        client_id,
        locked_clients,
        &WsMessage {
            msg_type: "client_hello".to_string(),
            room: None,
            client: Some(client_id.to_string()),
            payload: Some(serde_json::json!({ "client_id": client_id })),
            ts: now_ms(),
            server_ts: Some(now_ms()),
        },
    );
}

/// A client-supplied ID is only trusted if it actually looks like a UUIDv4
/// string generated by our own client (36 chars, hex + hyphens). Anything
/// else falls back to a freshly minted server-side ID. This isn't a secrecy
/// boundary (the ID is a bearer identifier, same trust model as a session
/// cookie) — it's just a sanity filter against garbage/oversized input.
fn is_plausible_client_id(id: &str) -> bool {
    id.len() == 36 && id.chars().all(|c| c.is_ascii_hexdigit() || c == '-')
}

pub async fn client_connection(
    ws: warp::ws::WebSocket,
    clients: Clients,
    rooms: Rooms,
    jwt_config: Arc<JwtConfig>,
    requested_client_id: Option<String>,
) {
    let (client_ws_sender, mut client_ws_rcv) = ws.split();
    let (client_sender, client_rcv) = mpsc::channel(CLIENT_CHANNEL_BUFFER);
    let client_rcv = ReceiverStream::new(client_rcv);

    tokio::task::spawn(async move {
        let _ = client_rcv.forward(client_ws_sender).await;
    });

    let client_id = requested_client_id
        .filter(|id| is_plausible_client_id(id))
        .unwrap_or_else(|| uuid::Uuid::new_v4().to_string());

    // If this ID already has an entry (a prior connection that's within its
    // reconnect grace period, or a stale one the zombie reaper hasn't gotten
    // to yet), reattach to it: swap in the new transport and keep whatever
    // room membership it already had. Otherwise register a brand-new client.
    let rejoined_room_id = {
        let mut locked_clients = clients.write().await;
        if let Some(existing) = locked_clients.get_mut(&client_id) {
            info!("Client {} reconnected (reattaching)", client_id);
            existing.sender = client_sender;
            existing.last_seen = now_ms();
            existing.room_id.clone()
        } else {
            info!(
                "Client connected: {} (auth_required: {})",
                client_id, jwt_config.enabled
            );
            let client = register_client(client_sender, &jwt_config);
            locked_clients.insert(client_id.clone(), client);
            None
        }
    };

    {
        let locked_clients = clients.read().await;
        send_client_hello(&client_id, &locked_clients);
    }

    send_room_list(&client_id, &clients, &rooms).await;

    if let Some(room_id) = rejoined_room_id {
        crate::room::resend_room_state(&client_id, &room_id, &clients, &rooms).await;
    }

    while let Some(result) = client_ws_rcv.next().await {
        if let Ok(msg) = result {
            client_msg(&client_id, msg, &clients, &rooms, &jwt_config).await;
        }
    }

    crate::room::schedule_disconnect(client_id, clients, rooms).await;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn register_client_jwt_disabled() {
        let (tx, _rx) = mpsc::channel(10);
        let jwt_config = Arc::new(JwtConfig {
            secret: String::new(),
            audience: "test".to_string(),
            issuer: "test".to_string(),
            enabled: false,
        });
        let client = register_client(tx, &jwt_config);
        assert!(client.authenticated);
        assert_eq!(client.user_id, "anonymous");
        assert_eq!(client.user_name, "Anonymous");
    }

    #[test]
    fn register_client_jwt_enabled() {
        let (tx, _rx) = mpsc::channel(10);
        let jwt_config = Arc::new(JwtConfig {
            secret: "some-secret".to_string(),
            audience: "test".to_string(),
            issuer: "test".to_string(),
            enabled: true,
        });
        let client = register_client(tx, &jwt_config);
        assert!(!client.authenticated);
        assert_eq!(client.user_id, "");
        assert_eq!(client.user_name, "");
    }

    #[test]
    fn plausible_client_id_accepts_uuid() {
        assert!(is_plausible_client_id(
            "550e8400-e29b-41d4-a716-446655440000"
        ));
    }

    #[test]
    fn plausible_client_id_rejects_garbage() {
        assert!(!is_plausible_client_id("not-a-uuid"));
        assert!(!is_plausible_client_id(""));
        assert!(!is_plausible_client_id(&"a".repeat(500)));
    }
}
